//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Element
    {
        public int ElementID { get; set; }
        public int PostID { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int Order { get; set; }
    
        public virtual Post Post { get; set; }
    }
}
